<?php

namespace Database\Seeders;

use App\Models\Car;
use App\Models\Category;
use Illuminate\Database\Seeder;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::all();

        $cars = [
            // سيارات اقتصادية
            [
                'category_id' => $categories->where('name_ar', 'سيارات اقتصادية')->first()->id,
                'brand_ar' => 'تويوتا',
                'brand_en' => 'Toyota',
                'model_ar' => 'كورولا',
                'model_en' => 'Corolla',
                'year' => 2023,
                'color_ar' => 'أبيض',
                'color_en' => 'White',
                'transmission' => 'أوتوماتيك',
                'fuel_type' => 'بنزين',
                'seats' => 5,
                'doors' => 4,
                'daily_rate' => 150.00,
                'weekly_rate' => 900.00,
                'monthly_rate' => 3000.00,
                'description_ar' => 'سيارة اقتصادية موثوقة ومناسبة للاستخدام اليومي',
                'description_en' => 'Reliable economy car suitable for daily use',
                'features' => ['مكيف هواء', 'نظام صوت', 'وسائد هوائية', 'نظام ABS'],
                'images' => ['/images/cars/toyota-corolla-1.jpg', '/images/cars/toyota-corolla-2.jpg'],
                'license_plate' => 'ABC-123',
                'vin' => '1HGBH41JXMN109186',
                'mileage' => 15000,
                'status' => 'available',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $categories->where('name_ar', 'سيارات اقتصادية')->first()->id,
                'brand_ar' => 'هيونداي',
                'brand_en' => 'Hyundai',
                'model_ar' => 'إلنترا',
                'model_en' => 'Elantra',
                'year' => 2022,
                'color_ar' => 'أزرق',
                'color_en' => 'Blue',
                'transmission' => 'أوتوماتيك',
                'fuel_type' => 'بنزين',
                'seats' => 5,
                'doors' => 4,
                'daily_rate' => 140.00,
                'weekly_rate' => 840.00,
                'monthly_rate' => 2800.00,
                'description_ar' => 'سيارة اقتصادية أنيقة مع تكنولوجيا حديثة',
                'description_en' => 'Stylish economy car with modern technology',
                'features' => ['مكيف هواء', 'نظام صوت', 'وسائد هوائية', 'كاميرا خلفية'],
                'images' => ['/images/cars/hyundai-elantra-1.jpg', '/images/cars/hyundai-elantra-2.jpg'],
                'license_plate' => 'DEF-456',
                'vin' => '2T1BURHE0JC123456',
                'mileage' => 12000,
                'status' => 'available',
                'is_featured' => false,
                'is_active' => true,
            ],
            // سيارات فاخرة
            [
                'category_id' => $categories->where('name_ar', 'سيارات فاخرة')->first()->id,
                'brand_ar' => 'مرسيدس',
                'brand_en' => 'Mercedes',
                'model_ar' => 'فئة S',
                'model_en' => 'S-Class',
                'year' => 2024,
                'color_ar' => 'أسود',
                'color_en' => 'Black',
                'transmission' => 'أوتوماتيك',
                'fuel_type' => 'بنزين',
                'seats' => 5,
                'doors' => 4,
                'daily_rate' => 800.00,
                'weekly_rate' => 4800.00,
                'monthly_rate' => 16000.00,
                'description_ar' => 'سيارة فاخرة من الدرجة الأولى مع أحدث التقنيات',
                'description_en' => 'First-class luxury car with latest technology',
                'features' => ['مقاعد جلدية', 'نظام صوت فاخر', 'مكيف هواء', 'نظام ملاحة', 'مقاعد مسخنة'],
                'images' => ['/images/cars/mercedes-s-class-1.jpg', '/images/cars/mercedes-s-class-2.jpg'],
                'license_plate' => 'GHI-789',
                'vin' => '3VWDX7AJ5DM123456',
                'mileage' => 5000,
                'status' => 'available',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $categories->where('name_ar', 'سيارات فاخرة')->first()->id,
                'brand_ar' => 'بي إم دبليو',
                'brand_en' => 'BMW',
                'model_ar' => 'فئة 7',
                'model_en' => '7 Series',
                'year' => 2023,
                'color_ar' => 'فضي',
                'color_en' => 'Silver',
                'transmission' => 'أوتوماتيك',
                'fuel_type' => 'بنزين',
                'seats' => 5,
                'doors' => 4,
                'daily_rate' => 750.00,
                'weekly_rate' => 4500.00,
                'monthly_rate' => 15000.00,
                'description_ar' => 'سيارة فاخرة رياضية مع أداء عالي',
                'description_en' => 'Luxury sports car with high performance',
                'features' => ['مقاعد جلدية', 'نظام صوت فاخر', 'مكيف هواء', 'نظام ملاحة', 'مقاعد مسخنة'],
                'images' => ['/images/cars/bmw-7-series-1.jpg', '/images/cars/bmw-7-series-2.jpg'],
                'license_plate' => 'JKL-012',
                'vin' => '4T1BF1FK5CU123456',
                'mileage' => 8000,
                'status' => 'available',
                'is_featured' => true,
                'is_active' => true,
            ],
            // سيارات رياضية
            [
                'category_id' => $categories->where('name_ar', 'سيارات رياضية')->first()->id,
                'brand_ar' => 'فيراري',
                'brand_en' => 'Ferrari',
                'model_ar' => '488',
                'model_en' => '488',
                'year' => 2023,
                'color_ar' => 'أحمر',
                'color_en' => 'Red',
                'transmission' => 'أوتوماتيك',
                'fuel_type' => 'بنزين',
                'seats' => 2,
                'doors' => 2,
                'daily_rate' => 1200.00,
                'weekly_rate' => 7200.00,
                'monthly_rate' => 24000.00,
                'description_ar' => 'سيارة رياضية خارقة مع أداء استثنائي',
                'description_en' => 'Super sports car with exceptional performance',
                'features' => ['مقاعد رياضية', 'نظام صوت فاخر', 'مكيف هواء', 'نظام ABS متقدم'],
                'images' => ['/images/cars/ferrari-488-1.jpg', '/images/cars/ferrari-488-2.jpg'],
                'license_plate' => 'MNO-345',
                'vin' => '5NPE34AF5FH123456',
                'mileage' => 3000,
                'status' => 'available',
                'is_featured' => true,
                'is_active' => true,
            ],
            // سيارات عائلية
            [
                'category_id' => $categories->where('name_ar', 'سيارات عائلية')->first()->id,
                'brand_ar' => 'هوندا',
                'brand_en' => 'Honda',
                'model_ar' => 'أوديسي',
                'model_en' => 'Odyssey',
                'year' => 2023,
                'color_ar' => 'رمادي',
                'color_en' => 'Gray',
                'transmission' => 'أوتوماتيك',
                'fuel_type' => 'بنزين',
                'seats' => 8,
                'doors' => 5,
                'daily_rate' => 200.00,
                'weekly_rate' => 1200.00,
                'monthly_rate' => 4000.00,
                'description_ar' => 'سيارة عائلية واسعة ومريحة للرحلات الطويلة',
                'description_en' => 'Spacious and comfortable family car for long trips',
                'features' => ['مقاعد متعددة', 'مكيف هواء', 'نظام صوت', 'وسائد هوائية', 'أبواب كهربائية'],
                'images' => ['/images/cars/honda-odyssey-1.jpg', '/images/cars/honda-odyssey-2.jpg'],
                'license_plate' => 'PQR-678',
                'vin' => '6G1ZT51806F123456',
                'mileage' => 18000,
                'status' => 'available',
                'is_featured' => false,
                'is_active' => true,
            ],
            // سيارات الدفع الرباعي
            [
                'category_id' => $categories->where('name_ar', 'سيارات الدفع الرباعي')->first()->id,
                'brand_ar' => 'تويوتا',
                'brand_en' => 'Toyota',
                'model_ar' => 'لاند كروزر',
                'model_en' => 'Land Cruiser',
                'year' => 2023,
                'color_ar' => 'أبيض',
                'color_en' => 'White',
                'transmission' => 'أوتوماتيك',
                'fuel_type' => 'بنزين',
                'seats' => 7,
                'doors' => 5,
                'daily_rate' => 400.00,
                'weekly_rate' => 2400.00,
                'monthly_rate' => 8000.00,
                'description_ar' => 'سيارة دفع رباعي قوية ومناسبة للمغامرات',
                'description_en' => 'Powerful SUV suitable for adventures',
                'features' => ['دفع رباعي', 'مكيف هواء', 'نظام صوت', 'وسائد هوائية', 'نظام ABS'],
                'images' => ['/images/cars/toyota-land-cruiser-1.jpg', '/images/cars/toyota-land-cruiser-2.jpg'],
                'license_plate' => 'STU-901',
                'vin' => '7FARW2H87BE123456',
                'mileage' => 25000,
                'status' => 'available',
                'is_featured' => false,
                'is_active' => true,
            ],
        ];

        foreach ($cars as $car) {
            // Check if car with this license plate already exists
            $existingCar = Car::where('license_plate', $car['license_plate'])->first();

            if (!$existingCar) {
                Car::create($car);
            }
        }
    }
}
